include:
  - ./services/mcaptcha/docker-compose.yml
services:
  minio:
    build:
      context: ./services/minio
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - ./services/minio/.env
    volumes:
      - ./services/minio/data:/data
    networks:
      - minio-net

  mongo:
    build:
      context: ./services/mongodb
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    env_file:
      - ./services/mongodb/.env
    volumes:
      - ./services/mongodb/data:/data/db
    networks:
      - mongo-net

  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./services/server/.env
    # Uncomment depends_on if needed for local development
    #depends_on:
    #  - mongo
    #  - mcaptcha
    networks:
      - minio-net
      - mongo-net
      - mcaptcha-net

networks:
  minio-net:
  mongo-net:
  mcaptcha-net: