services:
  minio:
    build:
      context: ./services/minio
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - ./services/minio/.env
      - .env
    volumes:
      - ./services/minio/data:/data

  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./services/server/.env
      - .env
    depends_on:
      - mongo
    volumes:
      - ./services/server:/app

  mongo:
    build:
      context: ./services/mongodb
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    env_file:
      - ./services/mongodb/.env
      - .env
    volumes:
      - ./services/mongodb/data:/data/db

