export enum AccountStatus {
  ANONYMOUS = 'ANONYMOUS',
  MFA_REQUIRED = 'MFA_REQUIRED',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  ONBOARDING = 'ONBOARDING',
  ONBOARDING_OAUTH = 'ONBOARDING_OAUTH',
  ACTIVE = 'ACTIVE',
  LOCKED = 'LOCKED',
  BANNED = 'BANNED',
  SOFT_DELETED = 'SOFT_DELETED'
}
