### Anonymously login
GET http://localhost:3000/v1/auth/


### Login
POST http://localhost:3000/v1/auth/
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJmNmZkMDc2Mi1kZjE2LTQxYmEtOGE2OC1lYzVjMmU2MGVhM2YiLCJhY2NvdW50U3RhdHVzIjoiYW5vbnltb3VzIiwiaWF0IjoxNzM5NTIwODAxLCJleHAiOjE3Mzk2MDcyMDF9.LCnTts7MxUoi4Y83oegk-wE29W5WdUZ4VLTEpda9hUs

{
    "username": "exampleUser", 
    "password": "Example@1234"
}

### Register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQ4ZDg3OC01Y2JmLTQzYmYtYmEzYS1mM2I2N2E4ZTQ4MjkiLCJhY2NvdW50U3RhdHVzIjoiYW5vbnltb3VzIiwiaWF0IjoxNzM5MjgwODgyLCJleHAiOjE3MzkzNjcyODJ9.hw_bqXr0OsdmwTEWyOKrdhBPaDIbUpLmglO3AYmUkwE

 {
    "username": "exampleUser", 
    "email": "example@example.com",
    "password": "Example@1234",
    "captchaToken": "dummyCaptchaToken" 
    }

#### 
POST http://localhost:3000/v1/auth/onboarding/oauth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2FlNDJlY2Q0ZGMzODNmZmUwYTAxODUiLCJhY2NvdW50U3RhdHVzIjoiYWN0aXZlIiwiaWF0IjoxNzM5NDc2MDM4LCJleHAiOjE3Mzk1NjI0Mzh9.NprzSlb1UEIPuf5dcgKa_5DPEc2GUdy8gFoMnTGI5_o

{
   "name": "John Doe",
   "birthday": "1990-01-01",
   "institute": "Tech University",
   "instituteIdentifier": "TU12345",
   "username": "john_doe123"
}